<a href="https://colab.research.google.com/github/VilasiniRamamoorthy/Mini_Project1/blob/main/sql_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SQL Analysis**

In [ ]:
%pip install pymysql

In [ ]:
%pip install pandas sqlalchemy pymysql

In [ ]:
#use tmdb_proj_vilasini;
#drop table cleaned_movies;
#drop table cleaned_movie_keywords;
#drop table cleaned_movie_generes;
#drop table cleaned_generes;
#drop table cleaned_crew;
#drop table cleaned_cast;

#commit;

#select * from cleaned_movies;
#select * from cleaned_movie_keywords;
#select * from cleaned_movie_generes;
#select * from cleaned_generes;
#select * from cleaned_crew;
#select * from cleaned_cast;


import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 1: List all movies in the Action genre released after 2015, showing title and release date JOIN (movies ⋈ movie_genres ⋈ genres)
with engine.connect() as conn:
    result = conn.execute(
        text("""SELECT A.movie_id, A.title, A.release_date
FROM CLEANED_MOVIES A,
     CLEANED_MOVIE_GENERES B,
     CLEANED_GENERES C
WHERE A.movie_id = B.movie_id
  AND B.genre_id = C.genre_id
  AND C.genre_name = 'Action'
  AND A.release_date >= '2016-01-01'
  order by A.release_date desc"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.6)
Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

     movie_id                         title release_date
0      931285              Mortal Kombat II   2026-05-06
1     1242898            Predator: Badlands   2025-11-05
2      617126  The Fantastic 4: First Steps   2025-07-23
3     1061474                      Superman   2025-07-09
4      911430                            F1   2025-06-25
..        ...                           ...          ...
263    146198                      Triple 9   2016-02-19
264    293660                      Deadpool   2016-02-09
265    329833                   Zoolander 2   2016-02-06
266    140300               Kung Fu Panda 3   2016-01-23
267    299687                  The 5th Wave   2016-01-14

[268 rows x 3 columns]

Total Records: 268

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 2: Find the top 10 highest-grossing movies along with the genre(s) each belongs to JOIN + ORDER BY + LIMIT
with engine.connect() as conn:
    result = conn.execute(
        text(""" SELECT A.movie_id, A.title, A.revenue,B.genre_id
FROM CLEANED_MOVIES A,
     CLEANED_MOVIE_GENERES B,
     CLEANED_GENERES C
WHERE A.movie_id = B.movie_id
  AND B.genre_id = C.genre_id
  AND A.revenue > 0
GROUP BY A.movie_id, A.title, A.revenue,B.genre_id
ORDER BY A.revenue DESC
LIMIT 10"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

   movie_id                     title       revenue  genre_id
0     19995                    Avatar  2.923706e+09        28
1     19995                    Avatar  2.923706e+09        12
2     19995                    Avatar  2.923706e+09       878
3    299534         Avengers: Endgame  2.799439e+09        12
4    299534         Avengers: Endgame  2.799439e+09        28
5    299534         Avengers: Endgame  2.799439e+09       878
6     76600  Avatar: The Way of Water  2.334485e+09       878
7     76600  Avatar: The Way of Water  2.334485e+09        28
8     76600  Avatar: The Way of Water  2.334485e+09        12
9       597                   Titanic  2.264162e+09        18

Total Records: 10

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 3: Calculate the average budget and average revenue for each genre, sorted by average revenue descending JOIN + GROUP BY + AVG()
with engine.connect() as conn:
    result = conn.execute(
        text(""" SELECT
    C.genre_id,
    C.genre_name,
    AVG(A.budget) AS avg_budget,
    AVG(A.revenue) AS avg_revenue
FROM CLEANED_MOVIES A
JOIN CLEANED_MOVIE_GENERES B
    ON A.movie_id = B.movie_id
JOIN CLEANED_GENERES C
    ON B.genre_id = C.genre_id
WHERE A.budget > 0
  AND A.revenue > 0
GROUP BY C.genre_id, C.genre_name
ORDER BY avg_revenue DESC"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

    genre_id       genre_name    avg_budget   avg_revenue
0         12        Adventure  1.100818e+08  3.958461e+08
1         16        Animation  8.632726e+07  3.670046e+08
2      10751           Family  8.688255e+07  3.495874e+08
3        878  Science Fiction  9.617939e+07  3.303115e+08
4         28           Action  9.389671e+07  3.061341e+08
5         14          Fantasy  8.786719e+07  3.004997e+08
6         99      Documentary  6.081643e+07  2.232790e+08
7         35           Comedy  5.472398e+07  2.216069e+08
8      10402            Music  4.355169e+07  2.020093e+08
9      10749          Romance  3.844483e+07  1.781441e+08
10        53         Thriller  5.155648e+07  1.704682e+08
11     10752              War  5.546687e+07  1.694554e+08
12     10770         TV Movie  3.320822e+07  1.674602e+08
13        80            Crime  4.723258e+07  1.552500e+08
14        37          Western  5.605554e+07  1.483732e+08
15      9648          Mystery  3.859328e+07  1.479339e+08
16        18            Drama  4.111822e+07  1.474669e+08
17        36          History  5.366279e+07  1.424488e+08
18        27           Horror  2.697331e+07  1.183882e+08

Total Records: 19

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 4: List the top 10 actors who have appeared in the most movies in the dataset.(cast) GROUP BY + COUNT()
with engine.connect() as conn:
    result = conn.execute(
        text(""" select actor_name, COUNT(DISTINCT movie_id) AS movie_count
from cleaned_cast
group by actor_name
order by movie_count desc"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

              actor_name  movie_count
0      Samuel L. Jackson           39
1              Brad Pitt           38
2         Robert De Niro           38
3            Johnny Depp           37
4              Tom Hanks           33
...                  ...          ...
11286       Ava McCarthy            1
11287     Juliet Doherty            1
11288       Lesley Boone            1
11289   Christopher Mele            1
11290       Jason Silvis            1

[11291 rows x 2 columns]

Total Records: 11291

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 5: Find all directors who have directed more than 3 movies, along with their movie count.	GROUP BY + HAVING
with engine.connect() as conn:
    result = conn.execute(
        text(""" select person_id,person_name, count(distinct movie_id) as movie_count
from cleaned_crew
where department='Directing'
group by person_id,person_name
having movie_count >3
order by movie_count desc"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

     person_id       person_name  movie_count
0          488  Steven Spielberg           27
1          578      Ridley Scott           19
2          510        Tim Burton           19
3         1032   Martin Scorsese           16
4          865       Michael Bay           15
..         ...               ...          ...
212      13848   Charlie Chaplin            4
213       9915      Guy Hamilton            4
214      12890       Pete Docter            4
215    1056121      Ryan Coogler            4
216      59291     Alexandre Aja            4

[217 rows x 3 columns]

Total Records: 217

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 6: List the top 10 most frequently used keywords across all movies.	GROUP BY + COUNT()
with engine.connect() as conn:
    result = conn.execute(
        text(""" select keyword_name, count(distinct movie_id) as movie_count
from cleaned_movie_keywords
group by keyword_name
order by movie_count DESC
limit 10"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

             keyword_name  movie_count
0  based on novel or book          449
1                  sequel          416
2    duringcreditsstinger          296
3     aftercreditsstinger          242
4                  murder          176
5     based on true story          166
6           new york city          161
7                 villain          160
8            3d animation          155
9          based on comic          154

Total Records: 10

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 7: Find movies where the budget was above the overall average budget but the revenue was below the overall average revenue.	Subquery comparison against AVG()
with engine.connect() as conn:
    result = conn.execute(
        text(""" select a.movie_id, a.title
from cleaned_movies a
where a.budget > (select avg(budget) from cleaned_movies where budget > 0)
and a.revenue < (select avg(revenue) from cleaned_movies where revenue > 0)"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

     movie_id                        title
0         550                   Fight Club
1      228150                         Fury
2        1949                       Zodiac
3      508442                         Soul
4         197                   Braveheart
..        ...                          ...
299     23488                  Dorian Gray
300     71880                Jack and Jill
301    629176                    Samaritan
302    967847  Ghostbusters: Frozen Empire
303   1368167                   Date Night

[304 rows x 2 columns]

Total Records: 304

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 8: List all actors who have appeared in a movie directed by a specific director (e.g., Christopher Nolan).	JOIN (cast ⋈ crew )
with engine.connect() as conn:
    result = conn.execute(
        text(""" select a.actor_name
from cleaned_cast a, cleaned_crew b
where a.movie_id = b.movie_id
and b.department = 'Directing'
and b.person_name ='Christopher Nolan'"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

              actor_name
0    Matthew McConaughey
1          Anne Hathaway
2          Michael Caine
3       Jessica Chastain
4          Casey Affleck
..                   ...
105        Josh Hartnett
106        Casey Affleck
107           Rami Malek
108      Kenneth Branagh
109         Benny Safdie

[110 rows x 1 columns]

Total Records: 110

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 9: Find the genre with the highest average rating, considering only genres with at least 20 movies.	JOIN + GROUP BY + HAVING + AVG()
with engine.connect() as conn:
    result = conn.execute(
        text(""" select a.genre_id, a.genre_name, count(distinct b.movie_id) as movie_count, avg(b.vote_average) as avg_rating
from cleaned_generes a,
cleaned_movies b,
cleaned_movie_generes c
where a.genre_id = c.genre_id
and c.movie_id = b.movie_id
group by a.genre_id,a.genre_name
having count(distinct b.movie_id) > 20
order by avg_rating desc"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

    genre_id       genre_name  movie_count  avg_rating
0      10752              War           85    7.357576
1         36          History          112    7.335509
2      10402            Music           49    7.324755
3         18            Drama          937    7.252454
4         16        Animation          246    7.204341
5         37          Western           33    7.131030
6      10749          Romance          349    7.033762
7         80            Crime          387    7.006690
8      10751           Family          344    6.935552
9       9648          Mystery          216    6.879625
10        53         Thriller          673    6.861853
11        12        Adventure          674    6.834755
12        14          Fantasy          396    6.825242
13       878  Science Fiction          463    6.814102
14        35           Comedy          762    6.809316
15        28           Action          808    6.729059
16        27           Horror          339    6.621224

Total Records: 17

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

#SQL 10: List the top 10 movies with the highest number of keywords tagged to them. 	JOIN + GROUP BY
with engine.connect() as conn:
    result = conn.execute(
        text(""" select a.movie_id,a.title,count(distinct b.keyword_name) as keyword_count
from cleaned_movies a, cleaned_movie_keywords b
where a.movie_id = b.movie_id
group by a.movie_id,a.title
order by keyword_count
limit 10"""))

 # Convert SQL result into Pandas DataFrame
    df_result = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

# Display interactive database-style table
display(df_result)

print("Total Records:", len(df_result))

engine.dispose()

   movie_id                             title  keyword_count
0    149509                             Horns              1
1    181812  Star Wars: The Rise of Skywalker              1
2     82520                            Return              1
3      6282                       Coyote Ugly              1
4    239571                    The Best of Me              2
5    762975                     Purple Hearts              2
6      9757                            Norbit              2
7    453405                        Gemini Man              2
8    403587                            Return              2
9    399035                      The Commuter              2

Total Records: 10